#The input file were generated by the command "vcftools --gzvcf input.vcf --missing-indv"

argv <- commandArgs(TRUE)
library(ggplot2)
pdf(paste(argv[1],".pdf",sep=""))
df=read.table(argv[1],header = T,sep = "\t")
df$group = substring(df$INDV, 1, 1)
library(ggplot2)
ggplot(df,aes(x=F_MISS,fill=group))+geom_histogram(bins = 100)+
facet_grid(group ~ .)
dev.off()